
name: Release

on:
  release:
    types: [ created ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Get the version
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Publish new image
      run: |
        mkdir tmp
        docker run -v "$PWD":/work cgr.dev/chainguard/apko build apko.yaml image:local tmp/image.tar

        docker tag image:local ghcr.io/altipla-consulting/distroless-mysqldump:latest
        docker push ghcr.io/altipla-consulting/distroless-mysqldump:latest
        
        docker tag image:local ghcr.io/altipla-consulting/distroless-mysqldump:${{ steps.version.outputs.VERSION }}
        docker push ghcr.io/altipla-consulting/distroless-mysqldump:${{ steps.version.outputs.VERSION }}
